name: dart_json_mapper_flutter
version: 1.0.3
description: >
  This is a dart-json-mapper complementary package
  provides support for https://github.com/flutter/flutter types in order to
  serialize / deserialize them from / to JSON.
homepage: https://github.com/k-paxian/dart-json-mapper/tree/master/adapters/flutter
environment:
  sdk: '>=2.3.1 <3.0.0'
dependencies:
  dart_json_mapper: '>=1.7.1 <3.0.0'
  flutter:
    sdk: flutter
dev_dependencies:
  reflectable:
  flutter_test:
    sdk: flutter
  pedantic:
  build_runner:
  build_test:
#dependency_overrides:
#  dart_json_mapper:
#    path: ../../mapper