name: dart_json_mapper_built
version: 0.0.1
description: >
  This is a dart-json-mapper complementary package
  provides support for https://pub.dev/packages/built_collection types in order to
  serialize / deserialize them from / to JSON.
homepage: https://github.com/k-paxian/dart-json-mapper/tree/master/adapters/built
environment:
  sdk: '>=2.3.1 <3.0.0'
dependencies:
  dart_json_mapper: '>=1.7.9 <3.0.0'
  built_collection: ^4.3.2
dev_dependencies:
  reflectable:
  pedantic:
  build_runner:
  build_test:
  test:
#dependency_overrides:
#  dart_json_mapper:
#    path: ../../mapper