name: dart_json_mapper
version: 2.0.5
description: >
  This package allows programmers to annotate Dart objects in order to
  serialize / deserialize them from / to JSON.
homepage: https://github.com/k-paxian/dart-json-mapper
environment:
  sdk: '>=2.12.0 <3.0.0'
dependencies:
  analyzer: '^1.1.0'
  build: ^2.0.0
  intl: ^0.17.0
  reflectable: ^3.0.0
  collection: ^1.15.0
dev_dependencies:
  pedantic: ^1.11.0
  build_runner:
  build_test:
  test:
