name: dart_json_mapper
version: 2.1.5
description: >
  This package allows programmers to annotate Dart objects in order to
  serialize / deserialize them from / to JSON.
homepage: https://github.com/k-paxian/dart-json-mapper
environment:
  sdk: '>=2.13.0 <3.0.0'
dependencies:
  analyzer: ^2.0.0
  build: ^2.1.0
  intl: ^0.17.0
  meta: ^1.7.0
  reflectable: ^3.0.3
  collection: ^1.15.0
dev_dependencies:
  lints:
  build_runner:
  build_test:
  test:
