name: dart_json_mapper
version: 2.2.3
description: >
  This package allows programmers to annotate Dart objects in order to
  serialize / deserialize them from / to JSON.
homepage: https://github.com/k-paxian/dart-json-mapper
environment:
  sdk: '>=2.15.1 <3.0.0'
dependencies:
  analyzer: ^3.4.1
  build: ^2.3.0
  intl: ^0.17.0
  meta: ^1.7.0
  path: ^1.8.1
  reflectable: ^3.0.8
  collection: ^1.16.0
  pubspec_parse: ^1.2.0
dev_dependencies:
  lints:
  build_runner:
