name: dart_json_mapper
version: 2.2.7+2
description: >
  This package allows programmers to annotate Dart objects in order to
  serialize / deserialize them from / to JSON.
homepage: https://github.com/k-paxian/dart-json-mapper
environment:
  sdk: '>=2.17.0 <3.0.0'
dependencies:
  analyzer: ^5.3.1
  build: ^2.3.1
  build_config: ^1.1.1
  intl: ^0.18.0
  meta: ^1.8.0
  path: ^1.8.3
  reflectable: ^4.0.4
  collection: ^1.17.0
  pubspec_parse: ^1.2.1
dev_dependencies:
  lints:
  build_runner:
