targets:
  $default:
    builders:
      dart_mappable_builder:
        generate_for:
          - test/starlink/dart_mappable/mappable_test.dart
      dart_json_mapper:
        options:
          iterables: List, Set
        generate_for:
          - test/unit/_test.dart
      reflectable:
        generate_for:
          - no/files