name: performance_test
# This package is not intended to be published
publish_to: none
description: >
  This package contains performance tests for the following JSON interoperability libraries:
  - JsonSerializable https://pub.dev/packages/json_serializable
  - BuiltValue https://pub.dev/packages/built_value
  - DartJsonMapper https://pub.dev/packages/dart_json_mapper
environment:
  sdk: '>=2.12.0 <3.0.0'
dependencies:
  dart_json_mapper:
  json_annotation: 4.0.1
  built_value: 8.1.1
  intl: ^0.17.0
dev_dependencies:
  json_serializable: 4.1.3
  built_value_generator: 8.1.1
  pedantic:
  build_runner:
  build_test:
  test:
dependency_overrides:
  dart_json_mapper:
    path: ../mapper