name: performance_test
# This package is not intended to be published
publish_to: none
description: >
  This package contains performance tests for the following JSON interoperability libraries:
  - JsonSerializable https://pub.dev/packages/json_serializable
  - BuiltValue https://pub.dev/packages/built_value
  - DartJsonMapper https://pub.dev/packages/dart_json_mapper
  - DartMappable https://pub.dev/packages/dart_mappable
  And unit tests for DartJsonMapper
homepage: https://github.com/k-paxian/dart-json-mapper/perf-test
environment:
  sdk: '>=2.13.0 <3.0.0'
dependencies:
  dart_json_mapper:
  json_annotation: 4.4.0
  built_value: 8.1.4
  dart_mappable:
  intl: ^0.17.0
dev_dependencies:
  json_serializable: 6.1.4
  built_value_generator: 8.1.4
  lints:
  build_runner:
  build_test:
  test:
dependency_overrides:
  unit_testing:
    path: ../models/unit_testing
  starlink:
    path: ../models/starlink
  dart_json_mapper:
    path: ../mapper